export const mockBusStopsAPIResponse: any = {
  type: "FeatureCollection",
  features: [
    {
      type: "Feature",
      id: "PARADES_ACTIVES.675582",
      geometry: {
        type: "Point",
        coordinates: [2.181499, 41.485729],
      },
      geometry_name: "GEOMETRY",
      properties: {
        ID_PARADA: 675582,
        CODI_PARADA: 1718,
        NOM_PARADA: "Av Riera de Sant Cugat - Ptge de la Pintura",
        DESC_PARADA: "Riera de Sant Cugat/Quarters",
        CODI_INTERC: 0,
        NOM_INTERC: null,
        NOM_TIPUS_PARADA: "PALFIX",
        NOM_TIPUS_SIMPLE_PARADA: "Pal",
        DESC_TIPUS_PARADA: "Parada Palfix",
        TIPIFICACIO_PARADA: "N",
        ADRECA: "Riera Sant Cugat, 11-13",
        ID_POBLACIO: 754,
        NOM_POBLACIO: "Montcada i Reixac",
        ID_DISTRICTE: 0,
        NOM_DISTRICTE: null,
        DATA: "2020-12-19Z",
        NOM_VIA: "Avinguda Riera de Sant Cugat",
        NOM_PROPERA_VIA: "Carrer Quarters",
        PUNTS_PARADA: 1,
      },
    },
    {
      type: "Feature",
      id: "PARADES_ACTIVES.677972",
      geometry: {
        type: "Point",
        coordinates: [2.178948, 41.48451],
      },
      geometry_name: "GEOMETRY",
      properties: {
        ID_PARADA: 677972,
        CODI_PARADA: 985,
        NOM_PARADA: "Av Riera de Sant Cugat - Huc de Montcada",
        DESC_PARADA: "Av.Riera Sant Cugat/Ptge.Hug de Montcada",
        CODI_INTERC: 0,
        NOM_INTERC: null,
        NOM_TIPUS_PARADA: "MAR4MS",
        NOM_TIPUS_SIMPLE_PARADA: "Marquesina ",
        DESC_TIPUS_PARADA: "Marq. Pal·li 4m Simple",
        TIPIFICACIO_PARADA: "N",
        ADRECA: "Riera Sant Cugat, 38",
        ID_POBLACIO: 754,
        NOM_POBLACIO: "Montcada i Reixac",
        ID_DISTRICTE: 0,
        NOM_DISTRICTE: null,
        DATA: "2020-12-19Z",
        NOM_VIA: "Avinguda Riera de Sant Cugat",
        NOM_PROPERA_VIA: "Passatge Huc de Montcada",
        PUNTS_PARADA: 1,
      },
    },
  ],
  totalFeatures: 135,
  numberMatched: 2,
  numberReturned: 2,
  timeStamp: "2020-10-19T06:44:29.076Z",
  crs: {
    type: "name",
    properties: {
      name: "urn:ogc:def:crs:EPSG::4326",
    },
  },
};

export const mockBusStopsResponse: any = [
  {
    id: "1718",
    location: {
      address: "Riera Sant Cugat, 11-13",
      city: "Montcada i Reixac",
      coordinates: { altitude: null, latitude: 41.485729, longitude: 2.181499 },
      district: null,
      street: "Avinguda Riera de Sant Cugat",
    },
    name: "Av Riera de Sant Cugat - Ptge de la Pintura",
  },
  {
    id: "985",
    location: {
      address: "Riera Sant Cugat, 38",
      city: "Montcada i Reixac",
      coordinates: { altitude: null, latitude: 41.48451, longitude: 2.178948 },
      district: null,
      street: "Avinguda Riera de Sant Cugat",
    },
    name: "Av Riera de Sant Cugat - Huc de Montcada",
  },
];
