name: Install, Build, Lint and Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: git checkout
        uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: node_modules cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: install
        run: yarn install --frozen-lockfile --link-duplicates
        env:
          CI: true

      - name: lint
        run: yarn lint
        env:
          CI: true

      - name: typecheck
        run: yarn typecheck
        env:
          CI: true

      - name: test
        run: yarn test:coverage
        env:
          CI: true

      - name: test coverage
        uses: coverallsapp/github-action@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          CI: true